### ISSUE TITLE
proxyjump to host alias over bastion/jump server

### ISSUE THREAD

**Issue by dirickxmaarten** [pkolano/ballast#6]
Is there a way for remote users to connect directly to a host alias through a bastion, similar to what the ProxyJump -J option allows?

As far as I understand, both proxyjump and proxycommand are not aware of any hosts defined in the remote/bastion ssh_config file. I'm trying to avoid opening up the ballast port to the internet, or installing ballast on remote users' machines.

Kind regards,
Maarten

**Comment by pkolano** [comment]
yes for proxycommand, but users on hosts beyond your control must add appropriate config into their ~/.ssh/config.  If you look at the ballast.1 man page in doc under "ssh configuration for external hosts", it shows you how.  If the hosts are still under your control, but on external networks (e.g. org-supported laptops), you could add the config to the global ssh_config so it was more transparent.

I don't know of an easy way to support this via proxyjump.  Could probably do it via some ld_preload magic in sshd, but would take more effort than just telling users to modify their config.

**Comment by dirickxmaarten** [comment]
Thanks @pkolano. I was secretly hoping there would be a ProxyJump way as well.  It's somehow hard to teach our users (scientists) to use the .ssh/config file. I often stumble across someone with an alias in .bashrc to an elaborate ssh command. Well, they do what they're trained to do: find a solution on their own. The `-J bastion` was starting the catch on, but I'll write another manual. Ironically, I was just proven to not read the manual thoroughly enough as well :)

Unfortunately, I run into another issue. With the `ProxyCommand ssh %r@bastion.example.com /usr/local/bin/ballast %h`, the ballast process is not terminated whenever a client disconnects. They get stuck in an infinite loop as shown by `strace`.  After some connects and disconnects, the processes stack up and the load on the bastion server increases.  I'm using the Perl script, and not the compiled C binaries.
```
select(8, [0 3], NULL, NULL, NULL)      = 1 (in [0])
read(0, "", 1048576)                    = 0
select(8, [0 3], NULL, NULL, NULL)      = 1 (in [0])
read(0, "", 1048576)                    = 0
```

This does not happen when the client connects from the bastion itself with the regular `ProxyCommand /usr/local/bin/ballast %h`.  

I have seen this before with `nc` where a `-w timeout` solves the issue. Funny enough, using `relay_path /usr/bin/netcat` without the -w argument does seem to fix this. Is this a known issue with the perl-script beta-featured relay?

Kind regards,
Maarten

**Comment by pkolano** [comment]
I think there are pros and cons to proxyjump vs. config file.  On the one hand, it's easy to just say -J with one extra host.  On the other hand, users have to do it every time unless they put it in a config file, at which point they could also just use proxycommand without much effort.  The beauty of a config file is that you can pretend you are directly connected to hosts without the bastion be it shell, remote command, or scp/sftp.  With -J, you always have to remember the bastion.  You can take a look at our docs for ideas if you want: https://www.nas.nasa.gov/hecc/support/kb/setting-up-ssh-passthrough_232.html. Here both "ssh-balance" and "ssh-proxy" are just ballast calls that have other names for historical purposes and "passthrough" is what we are calling the use of proxycommand.

The reason why -J doesn't work is because the balancing aliases are not real hosts so sshd can't resolve and connect to the ssh port.  One possible way to support this in a simple manner might be to create a cron job on the bastion that runs "ballast -l alias" every N minutes to get the currently selected host and update /etc/hosts to give the alias a real IP for sshd.  I'm sure there's some kind of caching that the system probably does that you might have to set to a time period less than the cron interval, but I believe you could get -J to work with such a thing.  Either that or some kind of local dynamic dns server (or other nsswitch-based mechanism) that could call out to ballast to get the current host name on-demand (no idea if such a thing exists, but would guess it does).

It could be that the built-in relay mechanism has the issue and now that you say that, I believe I did switch back to netcat after a time of using it for that reason.  Haven't had time to go back and look at the code and it is low priority since the external relay approach exists.  I believe netcat has gotten much better at detecting dropped connections.  We have used several mechanisms over the years and used to get zombie processes with netcat as well, but have not seen that problem in a long time.

**Comment by dirickxmaarten** [comment]
Understood, I'll stick to netcat.

The cron update of /etc/hosts is a perfect workaround. I don't think I will advertise/document it, but it is a nice safety net for those that have gotten too used to -J. 

Thank you for the support @pkolano!
